spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener
    username: {$USER_DATABASE}
    password: {$PASSWORD_DATABASE}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true